openapi: 3.0.0
info:
  title: derde api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /test/test1:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-test-test1
components:
  schemas: {}
