openapi: 3.0.0
info:
  title: tweede api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /hallo:
    get:
      summary: test
      tags: []
      responses: {}
      operationId: get-hallo
components:
  schemas: {}
