openapi: 3.0.0
info:
  title: API naam
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /testendpoint:
    get:
      summary: lucky
      tags: []
      responses: {}
      operationId: get-testendpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                test:
                  type: string
components:
  schemas: {}
