openapi: 3.0.0
info:
  title: Evolve API
  version: '1.0'
  description: Api description
servers:
  - url: 'http://localhost:8000'
paths:
  /users/test:
    get:
      summary: lucky
      tags: []
      responses: {}
      operationId: get-testendpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                test:
                  type: string
    parameters: []
  /users/test2:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users-test2
  /test/test:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-test-test
components:
  schemas:
    User:
      title: User
      type: object
      x-examples: {}
      properties:
        id:
          type: string
  securitySchemes: {}
