openapi: 3.0.0
info:
  title: Evolve API
  version: '1.0'
  description: |-
    Evolve API docs. Voulez-vous evolve avec moi ce soir?


    ### API connectie
    Voor connectie met de API loop de volgende stappen door:

    ```
    $ git checkout develop
    $ git pull develop
    $ source environment.bash
    $ pse_env
    $ > cd issue_tracker
    ```

    > (Optioneel) update database:
    > ```
    > $ > python3 manage.py migrate.py
    > ```

    > (Optioneel) reïnitialiseer database:
    > ```
    > $ > python3 manage.py makemigrations.py
    > $ > python3 manage.py migrate.py
    > ```

    ### Start webserver:
    ```
    $ > python3 manage.py runserver
    ```

    Connect met api-endpoints: `localhost:8000/api/endpoint`

    Open admin-(db)pagina: `localhost:8000/admin` en log in met: `superuser@test.nl` en`test`.

    <!-- theme: info -->

    > Als er geen superuser aangemaakt is kun je dat zelf doen:
    > ```
    > $ > python3 manage.py createsuperuser
    > ```
  contact: {}
servers:
  - url: 'http://localhost:8000'
paths:
  /course/create:
    post:
      summary: ''
      operationId: post-course-create
      responses:
        '200':
          description: OK
      description: Create a new course
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: ''
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
          format: password
        email:
          type: string
          format: email
        uva_id:
          type: integer
  securitySchemes: {}
